name = "TQC conference theme"
license = "MIT"
licenselink = "https://github.com/IAQI/tqc-website/blob/main/LICENSE"
description = "A hugo theme for a conference website. Originally created for DevFest Toulouse 2019, adapted for QCrypt conference, now used for TQC conference."
homepage = "https://github.com/IAQI/tqc-website/tree/main/themes/devfest-theme-hugo"
tags = ["conference", "TQC"]
features =  ["conference", "responsive"]
min_version = "0.50"


[author]
  name = "Christian Schaffner"
  homepage = "https://github.com/cschaffner"

[original]
  name = "GDG Toulouse"
  homepage = "//github.com/GDGToulouse"
